
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu May 05 15:07:16 VET 2016
//----------------------------------------------------

package Tiny;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int FUNCTION = 9;
  public static final int OVER = 27;
  public static final int DIFERENTE = 34;
  public static final int LPAREN = 28;
  public static final int SEMI = 32;
  public static final int REPEAT = 13;
  public static final int INT = 41;
  public static final int ARRAY = 47;
  public static final int LCORCHETE = 30;
  public static final int FOR = 33;
  public static final int MINUS = 25;
  public static final int WRITE = 16;
  public static final int RPAREN = 29;
  public static final int AND = 35;
  public static final int MENORIGUAL = 23;
  public static final int LT = 20;
  public static final int OR = 36;
  public static final int BEGIN = 6;
  public static final int UNTIL = 14;
  public static final int NUM = 17;
  public static final int PLUS = 24;
  public static final int ASSIGN = 18;
  public static final int IF = 2;
  public static final int ID = 44;
  public static final int OF = 46;
  public static final int MAYORIGUAL = 22;
  public static final int BOOLEAN = 43;
  public static final int EOF = 0;
  public static final int RETURN = 40;
  public static final int TRUE = 38;
  public static final int error = 1;
  public static final int PROGRAM = 10;
  public static final int BT = 21;
  public static final int VOID = 42;
  public static final int EQ = 19;
  public static final int DECLARE = 11;
  public static final int TIMES = 26;
  public static final int COLON = 37;
  public static final int ELSE = 4;
  public static final int READ = 15;
  public static final int TO = 12;
  public static final int WHILE = 5;
  public static final int RCORCHETE = 31;
  public static final int THEN = 3;
  public static final int END = 7;
  public static final int FALSE = 39;
  public static final int VAR = 45;
  public static final int DO = 8;
}

